-- Seed script for active_predicates table
-- Generated from production database on 2026-05-21
--
-- Usage:
--   psql -h localhost -U user -d noesis -f seed-active-predicates.sql
--
-- This script uses INSERT ... ON CONFLICT DO NOTHING so it is safe to run
-- on a database that already has some (or all) predicates seeded.
--
-- NOTES:
--   - Predicates labeled "ARE" and "OWN" (LLM extraction noise) have been
--     excluded.  They carry no useful semantic meaning for the graph.
--   - "IMPLEMENTES" was a misspelling in the DB; corrected to "IMPLEMENTS".
--
-- Groups (predicate_group):
--   DATA_LIFECYCLE    – CRUD, persistence, ingestion of data
--   COMMUNICATION     – messaging, events, notifications
--   EXECUTION_FLOW    – orchestration, invocation, processing
--   SECURITY_AUDIT    – auth, encryption, validation, monitoring
--   DATA_PROCESSING   – transformation, analysis, rendering
--   SYSTEM_INTEGRATION– dependencies, composition, extension
--   BUSINESS_RULES    – domain logic, defaults, uncategorized

INSERT INTO active_predicates (name, created_at, predicate_group) VALUES
('ACCEPTS',           NOW(), 'BUSINESS_RULES'),
('ADDS',              NOW(), 'DATA_LIFECYCLE'),
('AGGREGATES',        NOW(), 'DATA_PROCESSING'),
('ALERTS',            NOW(), 'COMMUNICATION'),
('ALLOWS',            NOW(), 'BUSINESS_RULES'),
('ANALYZES',          NOW(), 'DATA_PROCESSING'),
('ANSWERS',           NOW(), 'BUSINESS_RULES'),
('APPLIES',           NOW(), 'BUSINESS_RULES'),
('ARCHIVES',          NOW(), 'BUSINESS_RULES'),
('ARCHIVES_TO',       NOW(), 'BUSINESS_RULES'),
('ASSIGNED_TO',       NOW(), 'SYSTEM_INTEGRATION'),
('ATTACHES',          NOW(), 'SYSTEM_INTEGRATION'),
('AUTHENTICATES',     NOW(), 'SECURITY_AUDIT'),
('AUTHORIZES',        NOW(), 'SECURITY_AUDIT'),
('BASED_ON',          NOW(), 'SYSTEM_INTEGRATION'),
('BECOMES',           NOW(), 'BUSINESS_RULES'),
('BUILDS',            NOW(), 'DATA_PROCESSING'),
('CACHES',            NOW(), 'BUSINESS_RULES'),
('CALCULATES',        NOW(), 'BUSINESS_RULES'),
('CALLS',             NOW(), 'EXECUTION_FLOW'),
('CARRIES',           NOW(), 'BUSINESS_RULES'),
('CHECKS',            NOW(), 'SECURITY_AUDIT'),
('COLLECTS',          NOW(), 'BUSINESS_RULES'),
('CONFIGURED_BY',     NOW(), 'BUSINESS_RULES'),
('CONFIGURES',        NOW(), 'BUSINESS_RULES'),
('CONSISTS_OF',       NOW(), 'BUSINESS_RULES'),
('CONSUMED_ALONGSIDE',NOW(), 'COMMUNICATION'),
('CONSUMES',          NOW(), 'COMMUNICATION'),
('CONTACTS',          NOW(), 'COMMUNICATION'),
('CONTAINS',          NOW(), 'DATA_LIFECYCLE'),
('COORDINATES',       NOW(), 'EXECUTION_FLOW'),
('CORRELATES',        NOW(), 'DATA_PROCESSING'),
('COVERS',            NOW(), 'BUSINESS_RULES'),
('CREATES',           NOW(), 'DATA_LIFECYCLE'),
('DECRYPTS',          NOW(), 'SECURITY_AUDIT'),
('DEDUPLICATES',      NOW(), 'DATA_PROCESSING'),
('DEFINES',           NOW(), 'BUSINESS_RULES'),
('DELEGATES',         NOW(), 'EXECUTION_FLOW'),
('DELETES',           NOW(), 'DATA_LIFECYCLE'),
('DELIVERS',          NOW(), 'COMMUNICATION'),
('DEPENDS_ON',        NOW(), 'SYSTEM_INTEGRATION'),
('DETECTS',           NOW(), 'DATA_PROCESSING'),
('DISTINGUISHES',     NOW(), 'BUSINESS_RULES'),
('DRIVES',            NOW(), 'BUSINESS_RULES'),
('ENABLES',           NOW(), 'BUSINESS_RULES'),
('ENCRYPTS',          NOW(), 'SECURITY_AUDIT'),
('ENRICHES',          NOW(), 'BUSINESS_RULES'),
('ENSURES',           NOW(), 'BUSINESS_RULES'),
('ESTABLISHES',       NOW(), 'BUSINESS_RULES'),
('EVALUATES',         NOW(), 'DATA_PROCESSING'),
('EXECUTES',          NOW(), 'EXECUTION_FLOW'),
('EXPOSES',           NOW(), 'BUSINESS_RULES'),
('EXTENDS',           NOW(), 'SYSTEM_INTEGRATION'),
('EXTRACTS',          NOW(), 'DATA_PROCESSING'),
('FAILS_OVER',        NOW(), 'BUSINESS_RULES'),
('FEEDS',             NOW(), 'BUSINESS_RULES'),
('FETCHES',           NOW(), 'DATA_LIFECYCLE'),
('FILTERS',           NOW(), 'DATA_PROCESSING'),
('FLOW',              NOW(), 'BUSINESS_RULES'),
('FOLLOWS',           NOW(), 'BUSINESS_RULES'),
('FORWARDS',          NOW(), 'EXECUTION_FLOW'),
('GENERATES',         NOW(), 'DATA_PROCESSING'),
('GUARANTEES',        NOW(), 'BUSINESS_RULES'),
('HANDLES',           NOW(), 'BUSINESS_RULES'),
('HOLDS',             NOW(), 'DATA_LIFECYCLE'),
('IDENTIFIES',        NOW(), 'BUSINESS_RULES'),
('IMPLEMENTS',        NOW(), 'SYSTEM_INTEGRATION'),
('INCLUDES',          NOW(), 'DATA_LIFECYCLE'),
('INDEXES',           NOW(), 'DATA_PROCESSING'),
('INGESTS',           NOW(), 'DATA_LIFECYCLE'),
('INITIALIZES',       NOW(), 'BUSINESS_RULES'),
('INSTRUMENTS',       NOW(), 'BUSINESS_RULES'),
('INTEGRATES',        NOW(), 'SYSTEM_INTEGRATION'),
('INVOKES',           NOW(), 'EXECUTION_FLOW'),
('ISSUES',            NOW(), 'BUSINESS_RULES'),
('JOINS',             NOW(), 'BUSINESS_RULES'),
('LOGS',              NOW(), 'SECURITY_AUDIT'),
('MAINTAINED_BY',     NOW(), 'BUSINESS_RULES'),
('MAINTAINS',         NOW(), 'BUSINESS_RULES'),
('MANAGES',           NOW(), 'BUSINESS_RULES'),
('MANDATES',          NOW(), 'BUSINESS_RULES'),
('MAPS',              NOW(), 'DATA_PROCESSING'),
('MATCHES',           NOW(), 'BUSINESS_RULES'),
('MONITORS',          NOW(), 'SECURITY_AUDIT'),
('NEEDS',             NOW(), 'BUSINESS_RULES'),
('NEGOTIATES',        NOW(), 'BUSINESS_RULES'),
('NORMALIZES',        NOW(), 'DATA_PROCESSING'),
('NOTIFIES',          NOW(), 'BUSINESS_RULES'),
('OPERATES',          NOW(), 'BUSINESS_RULES'),
('ORCHESTRATES',      NOW(), 'EXECUTION_FLOW'),
('PARSES',            NOW(), 'DATA_PROCESSING'),
('PARTITIONS',        NOW(), 'BUSINESS_RULES'),
('PART_OF',           NOW(), 'SYSTEM_INTEGRATION'),
('PASSES',            NOW(), 'BUSINESS_RULES'),
('PERFORMS',          NOW(), 'EXECUTION_FLOW'),
('PERSISTS',          NOW(), 'DATA_LIFECYCLE'),
('PROCESSES',         NOW(), 'EXECUTION_FLOW'),
('PRODUCES',          NOW(), 'DATA_PROCESSING'),
('PROPAGATES',        NOW(), 'DATA_PROCESSING'),
('PROVIDES',          NOW(), 'BUSINESS_RULES'),
('PROVISIONS',        NOW(), 'BUSINESS_RULES'),
('PUBLISHES',         NOW(), 'COMMUNICATION'),
('QUERIES',           NOW(), 'BUSINESS_RULES'),
('READS',             NOW(), 'DATA_LIFECYCLE'),
('REASSIGNS',         NOW(), 'BUSINESS_RULES'),
('RECALCULATES',      NOW(), 'BUSINESS_RULES'),
('RECEIVES',          NOW(), 'COMMUNICATION'),
('RECONSTRUCTS',      NOW(), 'BUSINESS_RULES'),
('RECORDS',           NOW(), 'DATA_LIFECYCLE'),
('REGISTERS',         NOW(), 'BUSINESS_RULES'),
('RENDERS',           NOW(), 'DATA_PROCESSING'),
('REPLAYS',           NOW(), 'BUSINESS_RULES'),
('REPRESENTED_BY',    NOW(), 'BUSINESS_RULES'),
('REQUIRES',          NOW(), 'BUSINESS_RULES'),
('RESIDES',           NOW(), 'BUSINESS_RULES'),
('RESIDES_IN',        NOW(), 'BUSINESS_RULES'),
('RESPONDS',          NOW(), 'BUSINESS_RULES'),
('RESPONSIBLE_FOR',   NOW(), 'BUSINESS_RULES'),
('RETRIEVES',         NOW(), 'DATA_LIFECYCLE'),
('RETURNS',           NOW(), 'BUSINESS_RULES'),
('ROUTES',            NOW(), 'EXECUTION_FLOW'),
('RUNS',              NOW(), 'EXECUTION_FLOW'),
('SCALES',            NOW(), 'BUSINESS_RULES'),
('SCHEDULES',         NOW(), 'BUSINESS_RULES'),
('SCRAPES',           NOW(), 'DATA_PROCESSING'),
('SENDS',             NOW(), 'COMMUNICATION'),
('SEPARATES',         NOW(), 'BUSINESS_RULES'),
('SERVES',            NOW(), 'BUSINESS_RULES'),
('SHARED_ACROSS',     NOW(), 'BUSINESS_RULES'),
('SHARED_BY',         NOW(), 'BUSINESS_RULES'),
('SHARED_WITH',       NOW(), 'BUSINESS_RULES'),
('SHARES',            NOW(), 'BUSINESS_RULES'),
('SPECIFIES',         NOW(), 'BUSINESS_RULES'),
('SPLITS',            NOW(), 'DATA_PROCESSING'),
('STARTS',            NOW(), 'EXECUTION_FLOW'),
('STOPS',             NOW(), 'EXECUTION_FLOW'),
('STORES',            NOW(), 'DATA_LIFECYCLE'),
('SUBMITS',           NOW(), 'BUSINESS_RULES'),
('SUBSCRIBES',        NOW(), 'COMMUNICATION'),
('SUPPORTS',          NOW(), 'SYSTEM_INTEGRATION'),
('SYNCHRONIZES',      NOW(), 'BUSINESS_RULES'),
('TRACKS',            NOW(), 'SECURITY_AUDIT'),
('TRANSFORMS',        NOW(), 'DATA_PROCESSING'),
('TRANSITIONS',       NOW(), 'BUSINESS_RULES'),
('TRANSITIONS_TO',    NOW(), 'BUSINESS_RULES'),
('TRANSMITS',         NOW(), 'COMMUNICATION'),
('TRIGGERS',          NOW(), 'EXECUTION_FLOW'),
('UNDER',             NOW(), 'BUSINESS_RULES'),
('UPDATES',           NOW(), 'DATA_LIFECYCLE'),
('USES',              NOW(), 'SYSTEM_INTEGRATION'),
('VALIDATES',         NOW(), 'SECURITY_AUDIT'),
('VISUALIZES',        NOW(), 'DATA_PROCESSING'),
('WRITES',            NOW(), 'DATA_LIFECYCLE')
ON CONFLICT (name) DO NOTHING;
