package com.noesis.event;

public enum DocumentEventType {
    DOCUMENT_CREATED,
    DOCUMENT_UPDATED,
    DOCUMENT_DELETED,
    CHUNKING_COMPLETED,
    CHUNKING_FAILED,
    ASSERTION_EXTRACTION_COMPLETED,
    ASSERTION_EXTRACTION_FAILED,
    GRAPH_COMPONENTS_CREATED,
    ASSERTIONS_INDEXED,
    EDGES_INDEXED,
    CHUNK_GRAPH_READY,
    DOCUMENT_GRAPH_READY
}
